### ISSUE TITLE
Initial login to http://localhost:8080/static/admin/login.html ?

### ISSUE THREAD

**Issue by zopyx** [solisoft/fasty#4]
What are the initial credentials for the login or where can I set them?

**Comment by solisoft** [comment]
The default credentials is defined on `foxxy/foxx/auth/APP/scripts/setup.js`

```javascript
if(db.users.count() == 0) {
  db.users.save({
    username: 'demo@foxxy.ovh',
    authData: auth.create('977cebdd'),
    a: true,
    role: 'admin'
  })
} ```

I'll move it to a configuration page

**Comment by solisoft** [comment]
By the way you should access it via an url like : `http://demo.127.0.0.1.xip.io:8080/static/admin`

So it will use the `db_demo` database (you have to create it manually using arangodb admin UI
