### ISSUE TITLE
maybe im doing something wrong

### ISSUE THREAD

**Issue by seprator** [solisoft/fasty#44]
I'm getting this error when installing 

C:\Users\Click>foxxy upgrade settings --server foxxy --database db_demo
Foxxy - Version 0.6.19
internal/fs/utils.js:307
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\Click/.arangodb.yml'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at C:\Users\Click\AppData\Roaming\npm\node_modules\foxxy\bin\foxxy:331:45
    at C:\Users\Click\AppData\Roaming\npm\node_modules\foxxy\node_modules\hasbin\node_modules\async\lib\async.js:451:25
    at C:\Users\Click\AppData\Roaming\npm\node_modules\foxxy\node_modules\hasbin\lib\hasbin.js:72:3
    at FSReqCallback.oncomplete (fs.js:184:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Click/.arangodb.yml'
}

**Comment by solisoft** [comment]
oh well no ... please create an empty .arangodb.yml file, I'll check to remove this old dependency

**Comment by solisoft** [comment]
Notice that you have to run this command from the `$APP/foxxy` folder

Here my .arangodb.yml file
```
 cat .arangodb.yml
database: db_demo
username: root
password: 'password'
endpoint: 'http+tcp://127.0.0.1:8529'
```

which should be as well in the `$APP/foxxy` folder

**Comment by solisoft** [comment]
I just checked the file is present in the `$APP/foxxy` folder
https://github.com/solisoft/fasty/tree/master/foxxy

So your issue is because you are not running the command from the right folder.

Notice that I haven't test it on a windows ENV ... only OSX & Linux
