### ISSUE TITLE
noob issues

### ISSUE THREAD

**Issue by Lakedaemon** [solisoft/fasty#48]
Hello, I somewhat managed to set fasty up on my linux box, following the documentation.
I got the admin app running (looks raw but nice, fast and interesting, a developer's wet dream for a cms)

But alas, http://demo.localhost:8080/ gives me 

500 Internal Server Error
openresty/1.19.3.1

Where did I go wrong ?

Also the optional step
npm install fasty-cli -g 
failed for me with (picture enclosed) those errors
![buildFailed](https://user-images.githubusercontent.com/103175/119530183-11af5200-bd83-11eb-932a-675e71987e8d.png)

En tout cas, j'éspère pouvoir développer un site web à propos des mathématiques de l'enseignement supérieur avec une fonction de recherche hierarchique me permettant par exemple de trouver tous les concepts qui utilisent des applications (qui sont elles memes des fonctions qui sont un sous-ensemble de produit cartesien qui sont des ensembles).

La taxonomy et les fonctions de recherches de drupal (basée sur une base SQL) étant tellement limités, je me tourne vers arangodb & fasty

Best regards,
Olivier B

**Comment by Lakedaemon** [comment]
1) I tried setting it up on a vps to see if it would solve my issue (it didn't)
2) I started lloking at the code because I was wondering HOW I would set up a production website using fatsy with different login/passwords than root/password for the database (or everyone would be able to wipe my website up) and demo@foxxy.ovh :: 977cebdd for the cms backend

But I failed. 
I found the hardcoded password for the database in docker-compose.yml. But changing it did nothing (maybee because the arangodb image is setup with root/password...I'll try setting up another user and deletting root, this is probably the way to go)

I cannot enter the admin page (which is worse than before) 
and I still get a 500 error on port 8080/ (same as before).

oh well...gotta try harder :/

**Comment by Lakedaemon** [comment]
While waiting for help, I'll dump here what I discover about Fasty because it might help someone else.

Fasty looks to me like a  bunch of awesome tools, nicely glued together : 

1) arangoDB : multidocument database (key-values, graphs, ...) with Foxx is a JavaScript framework for writing data-centric HTTP microservices that run directly inside of ArangoDB.

That smells a lot like a headless cms...


2) openResty : enhanced nginx webserver with LUA,
Lapis a web framework to build web apps (with lua and moonscript (a dynamic script language that compiles to lua)) on openResty
RiotJS : Simple and elegant component-based UI library (in javascript)
 
That smells a lot like what is needed to write a head on top of a headless cms

So, what is fasty ? 
it is a tiny repository that builds the necessary docker files to host all of this
AND a few simple but efficient web apps that implement usefull things.

For exemple, the documentation explains in a few words How : 
- build and launch the docker file for arango/openResty
-  create a db_demo arango database 
- populate it with stuff that can be then used by the 
- files in static folder that implements the admin web app, by connecting stuff to the arango database and using riotJs components

And I wrongly assumed that the stuff in fasty was a production ready CMS, which explains why I was surprised that 
nothing would display on localhost:8080
-mostly because there is an admin web app, BUT there is NO webstite web app.

There are "deploy" choices in the admin web app, but maybee those do not work because I have not yet build a website web app

So, maybee I should BUILD a website web app (taking inspiration from the files in there) and use the admin stuff to manage it.


I'll look at the code some more and try to understand things further

**Comment by Lakedaemon** [comment]
mmmh, looking into the docker-compose.yml

there should be a cms and a cms_prod that run on different ports 8080 and 80, investigate that

**Comment by Lakedaemon** [comment]
Ok, some more thought : 
1) The dockerfile contains CMS and CMS_prod

to look at the website, I probably should have launched cms_prod AFTER I had populated the arangoDB with a stite through the CMS app

2) the infamous 
You need to create a ~/.foxxrc file with the content below
[server.foxxy]
url=http://localhost:8529
username=root
password=
happen because I am launching the command
sudo foxxy upgrade settings --server foxxy --database db_demo
(notice the sudo part)
So, it actually expects the ".foxxrc" file in the ROOT folder

3) Google chrome might do weird caching behind my back, which screw things up...I finally managed to setup /static/admin AGAIN but I had to use Firefox to access it...

Now that I have a local admin setup working, I might investigate the cms_prod thingie

**Comment by Lakedaemon** [comment]
mmmh, in static/admin...when I click "deploy", I get this : 
[C]: in function 'require'
cms_1       | 	/usr/local/share/lua/5.1/lapis/init.lua:15: in function 'serve'
cms_1       | 	content_by_lua(nginx.conf.compiled:65):2: in main chunk, client: 12.12.0.1, server: , request: "POST /deploy HTTP/1.1", host: "demo.localhost:8080", referrer: "http://demo.localhost:8080/static/admin/index.html"
cms_1       | 2021/05/28 05:13:37 [error] 24#0: *20 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/lapis/init.lua:15: module 'app' not found:
cms_1       | 	no field package.preload['app']
cms_1       | 	no file '/usr/local/openresty/site/lualib/app.ljbc'
cms_1       | 	no file '/usr/local/openresty/site/lualib/app/init.ljbc'
cms_1       | 	no file '/usr/local/openresty/lualib/app.ljbc'
cms_1       | 	no file '/usr/local/openresty/lualib/app/init.ljbc'
cms_1       | 	no file '/usr/local/openresty/site/lualib/app.lua'
cms_1       | 	no file '/usr/local/openresty/site/lualib/app/init.lua'
cms_1       | 	no file '/usr/local/openresty/lualib/app.lua'
cms_1       | 	no file '/usr/local/openresty/lualib/app/init.lua'
cms_1       | 	no file './app.lua'
cms_1       | 	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/app.lua'
cms_1       | 	no file '/usr/local/share/lua/5.1/app.lua'
cms_1       | 	no file '/usr/local/share/lua/5.1/app/init.lua'
cms_1       | 	no file '/usr/local/openresty/luajit/share/lua/5.1/app.lua'
cms_1       | 	no file '/usr/local/openresty/luajit/share/lua/5.1/app/init.lua'
cms_1       | 	no file '/usr/local/openresty/site/lualib/app.so'
cms_1       | 	no file '/usr/local/openresty/lualib/app.so'
cms_1       | 	no file './app.so'
cms_1       | 	no file '/usr/local/lib/lua/5.1/app.so'
cms_1       | 	no file '/usr/local/openresty/luajit/lib/lua/5.1/app.so'
cms_1       | 	no file '/usr/local/lib/lua/5.1/loadall.so'
cms_1       | stack traceback:
cms_1       | coroutine 0:
cms_1       | 	[C]: in function 'require'
cms_1       | 	/usr/local/share/lua/5.1/lapis/init.lua:15: in function 'serve'
cms_1       | 	content_by_lua(nginx.conf.compiled:65):2: in main chunk, client: 12.12.0.1, server: , request: "POST /deploy HTTP/1.1", host: "demo.localhost:8080", referrer: "http://demo.localhost:8080/static/admin/index.html"

something fishy is happening with the app thing (or maybe I need to build an app before I try to deploy things)

**Comment by Lakedaemon** [comment]
ok. It is possible to launch cms_prod
sudo docker-compose up cms_prod
[sudo] password for lakedaemon: 
fasty_arangodb_1 is up-to-date
Creating fasty_cms_prod_1 ... done
Attaching to fasty_cms_prod_1
cms_prod_1  | Built app.moon
cms_prod_1  | Built config.moon
cms_prod_1  | Built applications/assets.moon
cms_prod_1  | Built applications/services.moon
cms_prod_1  | Built applications/uploads.moon
cms_prod_1  | Built lib/aqls.moon
cms_prod_1  | Built lib/arango.moon
cms_prod_1  | Built lib/basic_auth.moon
cms_prod_1  | Built lib/concerns.moon
cms_prod_1  | Built lib/http_client.moon
cms_prod_1  | Built lib/service.moon
cms_prod_1  | Built lib/utils.moon
cms_prod_1  | Built spec/page_spec.moon
cms_prod_1  | 2021/05/28 05:17:24 [notice] 29#0: using the "epoll" event method
cms_prod_1  | 2021/05/28 05:17:24 [notice] 29#0: openresty/1.19.3.1
cms_prod_1  | 2021/05/28 05:17:24 [notice] 29#0: built by gcc 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
cms_prod_1  | 2021/05/28 05:17:24 [notice] 29#0: OS: Linux 5.4.0-73-generic
cms_prod_1  | 2021/05/28 05:17:24 [notice] 29#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
cms_prod_1  | 2021/05/28 05:17:24 [notice] 29#0: start worker processes
cms_prod_1  | 2021/05/28 05:17:24 [notice] 29#0: start worker process 30
cms_prod_1  | 2021/05/28 05:17:24 [notice] 29#0: start worker process 31
cms_prod_1  | 2021/05/28 05:17:24 [notice] 29#0: start worker process 32
cms_prod_1  | 2021/05/28 05:17:24 [notice] 29#0: start worker process 33


yet, it demo.localhost and demo.localhost:80 give me this (same thing if I had /home)

This site can’t be reached
demo.localhost refused to connect.

Unable to connect
Firefox can’t establish a connection to the server at demo.localhost.

BUT http://demo.localhost:9090 gives me the infamous (same with /home)

500 Internal Server Error
openresty/1.19.3.1

So, be it cms or cms_prod there is no website (probably because I HAVE to build an app first, investigating that now)

oh, I managed to login in http://demo.localhost:9090/static/admin/
So, cms_prod is actually just like cms on steroids (with more workers and cache enabled)

So, I have to write an app, but how? documentation leaves me in the dust here...
I'll look at the sparse videos I found while investigating now and try something

**Comment by solisoft** [comment]
Hi Sorry just saw your messages... 
I'll be glad to help you on your setup. Maybe I made something wrong in the doc ? 

Anyway please contact me on discord https://discord.gg/yNbf3DCw

We can do some pair setup stuff ;)

**Comment by solisoft** [comment]
So about your issues, you need to be able to compile sass npm module ... 
The password can be changed in the admin part (check users)
For the `cms` docker compose service you need to compile *.moon files first
Then you have to go to the admin > pages and edit the page and save it

**Comment by solisoft** [comment]
Fasty is not only a docker compose file ;) it allow you very nice features out of the box. 
- I18n, image uploads, form creator, image resizing on the fly (and format converter), API builder (foxx), manage small nodejs apps (think about a real time socket.io app), manage functions (extend the controllers with apps in lua or any external language (must be installed in the docker file), etc ...
